// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Request.proto

package distributedlock;

public final class RequestProto {
  private RequestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ClockMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:distributedlock.ClockMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>required int32 val = 2;</code>
     */
    boolean hasVal();
    /**
     * <code>required int32 val = 2;</code>
     */
    int getVal();
  }
  /**
   * Protobuf type {@code distributedlock.ClockMsg}
   */
  public static final class ClockMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:distributedlock.ClockMsg)
      ClockMsgOrBuilder {
    // Use ClockMsg.newBuilder() to construct.
    private ClockMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ClockMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ClockMsg defaultInstance;
    public static ClockMsg getDefaultInstance() {
      return defaultInstance;
    }

    public ClockMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ClockMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              val_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return distributedlock.RequestProto.internal_static_distributedlock_ClockMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return distributedlock.RequestProto.internal_static_distributedlock_ClockMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              distributedlock.RequestProto.ClockMsg.class, distributedlock.RequestProto.ClockMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<ClockMsg> PARSER =
        new com.google.protobuf.AbstractParser<ClockMsg>() {
      public ClockMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ClockMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ClockMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int VAL_FIELD_NUMBER = 2;
    private int val_;
    /**
     * <code>required int32 val = 2;</code>
     */
    public boolean hasVal() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 val = 2;</code>
     */
    public int getVal() {
      return val_;
    }

    private void initFields() {
      id_ = 0;
      val_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVal()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, val_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, val_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static distributedlock.RequestProto.ClockMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static distributedlock.RequestProto.ClockMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static distributedlock.RequestProto.ClockMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static distributedlock.RequestProto.ClockMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static distributedlock.RequestProto.ClockMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static distributedlock.RequestProto.ClockMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static distributedlock.RequestProto.ClockMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static distributedlock.RequestProto.ClockMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static distributedlock.RequestProto.ClockMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static distributedlock.RequestProto.ClockMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(distributedlock.RequestProto.ClockMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code distributedlock.ClockMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:distributedlock.ClockMsg)
        distributedlock.RequestProto.ClockMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return distributedlock.RequestProto.internal_static_distributedlock_ClockMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return distributedlock.RequestProto.internal_static_distributedlock_ClockMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                distributedlock.RequestProto.ClockMsg.class, distributedlock.RequestProto.ClockMsg.Builder.class);
      }

      // Construct using distributedlock.RequestProto.ClockMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        val_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return distributedlock.RequestProto.internal_static_distributedlock_ClockMsg_descriptor;
      }

      public distributedlock.RequestProto.ClockMsg getDefaultInstanceForType() {
        return distributedlock.RequestProto.ClockMsg.getDefaultInstance();
      }

      public distributedlock.RequestProto.ClockMsg build() {
        distributedlock.RequestProto.ClockMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public distributedlock.RequestProto.ClockMsg buildPartial() {
        distributedlock.RequestProto.ClockMsg result = new distributedlock.RequestProto.ClockMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.val_ = val_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof distributedlock.RequestProto.ClockMsg) {
          return mergeFrom((distributedlock.RequestProto.ClockMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(distributedlock.RequestProto.ClockMsg other) {
        if (other == distributedlock.RequestProto.ClockMsg.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasVal()) {
          setVal(other.getVal());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasVal()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        distributedlock.RequestProto.ClockMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (distributedlock.RequestProto.ClockMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private int val_ ;
      /**
       * <code>required int32 val = 2;</code>
       */
      public boolean hasVal() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 val = 2;</code>
       */
      public int getVal() {
        return val_;
      }
      /**
       * <code>required int32 val = 2;</code>
       */
      public Builder setVal(int value) {
        bitField0_ |= 0x00000002;
        val_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 val = 2;</code>
       */
      public Builder clearVal() {
        bitField0_ = (bitField0_ & ~0x00000002);
        val_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:distributedlock.ClockMsg)
    }

    static {
      defaultInstance = new ClockMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:distributedlock.ClockMsg)
  }

  public interface RequestMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:distributedlock.RequestMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 pid = 1;</code>
     */
    boolean hasPid();
    /**
     * <code>required int32 pid = 1;</code>
     */
    int getPid();

    /**
     * <code>repeated .distributedlock.ClockMsg clocks = 2;</code>
     */
    java.util.List<distributedlock.RequestProto.ClockMsg> 
        getClocksList();
    /**
     * <code>repeated .distributedlock.ClockMsg clocks = 2;</code>
     */
    distributedlock.RequestProto.ClockMsg getClocks(int index);
    /**
     * <code>repeated .distributedlock.ClockMsg clocks = 2;</code>
     */
    int getClocksCount();
    /**
     * <code>repeated .distributedlock.ClockMsg clocks = 2;</code>
     */
    java.util.List<? extends distributedlock.RequestProto.ClockMsgOrBuilder> 
        getClocksOrBuilderList();
    /**
     * <code>repeated .distributedlock.ClockMsg clocks = 2;</code>
     */
    distributedlock.RequestProto.ClockMsgOrBuilder getClocksOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code distributedlock.RequestMsg}
   */
  public static final class RequestMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:distributedlock.RequestMsg)
      RequestMsgOrBuilder {
    // Use RequestMsg.newBuilder() to construct.
    private RequestMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RequestMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RequestMsg defaultInstance;
    public static RequestMsg getDefaultInstance() {
      return defaultInstance;
    }

    public RequestMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RequestMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              pid_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                clocks_ = new java.util.ArrayList<distributedlock.RequestProto.ClockMsg>();
                mutable_bitField0_ |= 0x00000002;
              }
              clocks_.add(input.readMessage(distributedlock.RequestProto.ClockMsg.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          clocks_ = java.util.Collections.unmodifiableList(clocks_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return distributedlock.RequestProto.internal_static_distributedlock_RequestMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return distributedlock.RequestProto.internal_static_distributedlock_RequestMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              distributedlock.RequestProto.RequestMsg.class, distributedlock.RequestProto.RequestMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<RequestMsg> PARSER =
        new com.google.protobuf.AbstractParser<RequestMsg>() {
      public RequestMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RequestMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int PID_FIELD_NUMBER = 1;
    private int pid_;
    /**
     * <code>required int32 pid = 1;</code>
     */
    public boolean hasPid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 pid = 1;</code>
     */
    public int getPid() {
      return pid_;
    }

    public static final int CLOCKS_FIELD_NUMBER = 2;
    private java.util.List<distributedlock.RequestProto.ClockMsg> clocks_;
    /**
     * <code>repeated .distributedlock.ClockMsg clocks = 2;</code>
     */
    public java.util.List<distributedlock.RequestProto.ClockMsg> getClocksList() {
      return clocks_;
    }
    /**
     * <code>repeated .distributedlock.ClockMsg clocks = 2;</code>
     */
    public java.util.List<? extends distributedlock.RequestProto.ClockMsgOrBuilder> 
        getClocksOrBuilderList() {
      return clocks_;
    }
    /**
     * <code>repeated .distributedlock.ClockMsg clocks = 2;</code>
     */
    public int getClocksCount() {
      return clocks_.size();
    }
    /**
     * <code>repeated .distributedlock.ClockMsg clocks = 2;</code>
     */
    public distributedlock.RequestProto.ClockMsg getClocks(int index) {
      return clocks_.get(index);
    }
    /**
     * <code>repeated .distributedlock.ClockMsg clocks = 2;</code>
     */
    public distributedlock.RequestProto.ClockMsgOrBuilder getClocksOrBuilder(
        int index) {
      return clocks_.get(index);
    }

    private void initFields() {
      pid_ = 0;
      clocks_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasPid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getClocksCount(); i++) {
        if (!getClocks(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, pid_);
      }
      for (int i = 0; i < clocks_.size(); i++) {
        output.writeMessage(2, clocks_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, pid_);
      }
      for (int i = 0; i < clocks_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, clocks_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static distributedlock.RequestProto.RequestMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static distributedlock.RequestProto.RequestMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static distributedlock.RequestProto.RequestMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static distributedlock.RequestProto.RequestMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static distributedlock.RequestProto.RequestMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static distributedlock.RequestProto.RequestMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static distributedlock.RequestProto.RequestMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static distributedlock.RequestProto.RequestMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static distributedlock.RequestProto.RequestMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static distributedlock.RequestProto.RequestMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(distributedlock.RequestProto.RequestMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code distributedlock.RequestMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:distributedlock.RequestMsg)
        distributedlock.RequestProto.RequestMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return distributedlock.RequestProto.internal_static_distributedlock_RequestMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return distributedlock.RequestProto.internal_static_distributedlock_RequestMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                distributedlock.RequestProto.RequestMsg.class, distributedlock.RequestProto.RequestMsg.Builder.class);
      }

      // Construct using distributedlock.RequestProto.RequestMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getClocksFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        pid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (clocksBuilder_ == null) {
          clocks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          clocksBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return distributedlock.RequestProto.internal_static_distributedlock_RequestMsg_descriptor;
      }

      public distributedlock.RequestProto.RequestMsg getDefaultInstanceForType() {
        return distributedlock.RequestProto.RequestMsg.getDefaultInstance();
      }

      public distributedlock.RequestProto.RequestMsg build() {
        distributedlock.RequestProto.RequestMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public distributedlock.RequestProto.RequestMsg buildPartial() {
        distributedlock.RequestProto.RequestMsg result = new distributedlock.RequestProto.RequestMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.pid_ = pid_;
        if (clocksBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            clocks_ = java.util.Collections.unmodifiableList(clocks_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.clocks_ = clocks_;
        } else {
          result.clocks_ = clocksBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof distributedlock.RequestProto.RequestMsg) {
          return mergeFrom((distributedlock.RequestProto.RequestMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(distributedlock.RequestProto.RequestMsg other) {
        if (other == distributedlock.RequestProto.RequestMsg.getDefaultInstance()) return this;
        if (other.hasPid()) {
          setPid(other.getPid());
        }
        if (clocksBuilder_ == null) {
          if (!other.clocks_.isEmpty()) {
            if (clocks_.isEmpty()) {
              clocks_ = other.clocks_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureClocksIsMutable();
              clocks_.addAll(other.clocks_);
            }
            onChanged();
          }
        } else {
          if (!other.clocks_.isEmpty()) {
            if (clocksBuilder_.isEmpty()) {
              clocksBuilder_.dispose();
              clocksBuilder_ = null;
              clocks_ = other.clocks_;
              bitField0_ = (bitField0_ & ~0x00000002);
              clocksBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getClocksFieldBuilder() : null;
            } else {
              clocksBuilder_.addAllMessages(other.clocks_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasPid()) {
          
          return false;
        }
        for (int i = 0; i < getClocksCount(); i++) {
          if (!getClocks(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        distributedlock.RequestProto.RequestMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (distributedlock.RequestProto.RequestMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int pid_ ;
      /**
       * <code>required int32 pid = 1;</code>
       */
      public boolean hasPid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 pid = 1;</code>
       */
      public int getPid() {
        return pid_;
      }
      /**
       * <code>required int32 pid = 1;</code>
       */
      public Builder setPid(int value) {
        bitField0_ |= 0x00000001;
        pid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 pid = 1;</code>
       */
      public Builder clearPid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        pid_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<distributedlock.RequestProto.ClockMsg> clocks_ =
        java.util.Collections.emptyList();
      private void ensureClocksIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          clocks_ = new java.util.ArrayList<distributedlock.RequestProto.ClockMsg>(clocks_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          distributedlock.RequestProto.ClockMsg, distributedlock.RequestProto.ClockMsg.Builder, distributedlock.RequestProto.ClockMsgOrBuilder> clocksBuilder_;

      /**
       * <code>repeated .distributedlock.ClockMsg clocks = 2;</code>
       */
      public java.util.List<distributedlock.RequestProto.ClockMsg> getClocksList() {
        if (clocksBuilder_ == null) {
          return java.util.Collections.unmodifiableList(clocks_);
        } else {
          return clocksBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .distributedlock.ClockMsg clocks = 2;</code>
       */
      public int getClocksCount() {
        if (clocksBuilder_ == null) {
          return clocks_.size();
        } else {
          return clocksBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .distributedlock.ClockMsg clocks = 2;</code>
       */
      public distributedlock.RequestProto.ClockMsg getClocks(int index) {
        if (clocksBuilder_ == null) {
          return clocks_.get(index);
        } else {
          return clocksBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .distributedlock.ClockMsg clocks = 2;</code>
       */
      public Builder setClocks(
          int index, distributedlock.RequestProto.ClockMsg value) {
        if (clocksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureClocksIsMutable();
          clocks_.set(index, value);
          onChanged();
        } else {
          clocksBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .distributedlock.ClockMsg clocks = 2;</code>
       */
      public Builder setClocks(
          int index, distributedlock.RequestProto.ClockMsg.Builder builderForValue) {
        if (clocksBuilder_ == null) {
          ensureClocksIsMutable();
          clocks_.set(index, builderForValue.build());
          onChanged();
        } else {
          clocksBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .distributedlock.ClockMsg clocks = 2;</code>
       */
      public Builder addClocks(distributedlock.RequestProto.ClockMsg value) {
        if (clocksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureClocksIsMutable();
          clocks_.add(value);
          onChanged();
        } else {
          clocksBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .distributedlock.ClockMsg clocks = 2;</code>
       */
      public Builder addClocks(
          int index, distributedlock.RequestProto.ClockMsg value) {
        if (clocksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureClocksIsMutable();
          clocks_.add(index, value);
          onChanged();
        } else {
          clocksBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .distributedlock.ClockMsg clocks = 2;</code>
       */
      public Builder addClocks(
          distributedlock.RequestProto.ClockMsg.Builder builderForValue) {
        if (clocksBuilder_ == null) {
          ensureClocksIsMutable();
          clocks_.add(builderForValue.build());
          onChanged();
        } else {
          clocksBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .distributedlock.ClockMsg clocks = 2;</code>
       */
      public Builder addClocks(
          int index, distributedlock.RequestProto.ClockMsg.Builder builderForValue) {
        if (clocksBuilder_ == null) {
          ensureClocksIsMutable();
          clocks_.add(index, builderForValue.build());
          onChanged();
        } else {
          clocksBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .distributedlock.ClockMsg clocks = 2;</code>
       */
      public Builder addAllClocks(
          java.lang.Iterable<? extends distributedlock.RequestProto.ClockMsg> values) {
        if (clocksBuilder_ == null) {
          ensureClocksIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, clocks_);
          onChanged();
        } else {
          clocksBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .distributedlock.ClockMsg clocks = 2;</code>
       */
      public Builder clearClocks() {
        if (clocksBuilder_ == null) {
          clocks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          clocksBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .distributedlock.ClockMsg clocks = 2;</code>
       */
      public Builder removeClocks(int index) {
        if (clocksBuilder_ == null) {
          ensureClocksIsMutable();
          clocks_.remove(index);
          onChanged();
        } else {
          clocksBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .distributedlock.ClockMsg clocks = 2;</code>
       */
      public distributedlock.RequestProto.ClockMsg.Builder getClocksBuilder(
          int index) {
        return getClocksFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .distributedlock.ClockMsg clocks = 2;</code>
       */
      public distributedlock.RequestProto.ClockMsgOrBuilder getClocksOrBuilder(
          int index) {
        if (clocksBuilder_ == null) {
          return clocks_.get(index);  } else {
          return clocksBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .distributedlock.ClockMsg clocks = 2;</code>
       */
      public java.util.List<? extends distributedlock.RequestProto.ClockMsgOrBuilder> 
           getClocksOrBuilderList() {
        if (clocksBuilder_ != null) {
          return clocksBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(clocks_);
        }
      }
      /**
       * <code>repeated .distributedlock.ClockMsg clocks = 2;</code>
       */
      public distributedlock.RequestProto.ClockMsg.Builder addClocksBuilder() {
        return getClocksFieldBuilder().addBuilder(
            distributedlock.RequestProto.ClockMsg.getDefaultInstance());
      }
      /**
       * <code>repeated .distributedlock.ClockMsg clocks = 2;</code>
       */
      public distributedlock.RequestProto.ClockMsg.Builder addClocksBuilder(
          int index) {
        return getClocksFieldBuilder().addBuilder(
            index, distributedlock.RequestProto.ClockMsg.getDefaultInstance());
      }
      /**
       * <code>repeated .distributedlock.ClockMsg clocks = 2;</code>
       */
      public java.util.List<distributedlock.RequestProto.ClockMsg.Builder> 
           getClocksBuilderList() {
        return getClocksFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          distributedlock.RequestProto.ClockMsg, distributedlock.RequestProto.ClockMsg.Builder, distributedlock.RequestProto.ClockMsgOrBuilder> 
          getClocksFieldBuilder() {
        if (clocksBuilder_ == null) {
          clocksBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              distributedlock.RequestProto.ClockMsg, distributedlock.RequestProto.ClockMsg.Builder, distributedlock.RequestProto.ClockMsgOrBuilder>(
                  clocks_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          clocks_ = null;
        }
        return clocksBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:distributedlock.RequestMsg)
    }

    static {
      defaultInstance = new RequestMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:distributedlock.RequestMsg)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_distributedlock_ClockMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_distributedlock_ClockMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_distributedlock_RequestMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_distributedlock_RequestMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rRequest.proto\022\017distributedlock\"#\n\010Cloc" +
      "kMsg\022\n\n\002id\030\001 \002(\005\022\013\n\003val\030\002 \002(\005\"D\n\nRequest" +
      "Msg\022\013\n\003pid\030\001 \002(\005\022)\n\006clocks\030\002 \003(\0132\031.distr" +
      "ibutedlock.ClockMsgB\016B\014RequestProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_distributedlock_ClockMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_distributedlock_ClockMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_distributedlock_ClockMsg_descriptor,
        new java.lang.String[] { "Id", "Val", });
    internal_static_distributedlock_RequestMsg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_distributedlock_RequestMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_distributedlock_RequestMsg_descriptor,
        new java.lang.String[] { "Pid", "Clocks", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
